
http:
  host: "localhost"
  port: "8082"
  
db:
  username: "root"
  password: "root"
  host: "localhost"
  port: "3306"
  database: "MEMF"
Activemq:
  username: "admin"
  password: "admin"
  url: "tcp://localhost:61616"
  
environment: "prod"
applicationName: "mss-memf-generic-event-producer-sapi-v2"

